# tentacle_mod: Rig module for tentacle, tail, stretchy spine, etc. Works well with flexi cloth setup.

[[rig_module]]
rig_module = "tentacle_mod" 
rig_module_name = "tail"
joints = "tail_01_jnt, tail_09_jnt"
flexi_joints_main = "tailCloth_01_jnt, tailCloth_09_jnt"
flexi_joints_offset = "tailClothFlexi_start_jnt, tailClothFlexi_end_jnt"
get_joint_chain = true
flexi_surface_main = "flexiSurfaceTailMain_geo"
flexi_surface_offset = "flexiSurfaceTailStretch_geo"


# ----------

[[rig_module]]
rig_module = "fk_control_mod" 
rig_module_name = "root" 
joints = "root_jnt"

[[rig_module]]
rig_module = "fk_control_mod" 
rig_module_name = "pelvis" 
joints = "pelvis_jnt"